name: Cogwork Media
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bdcbd4'
    - '#4d4d4d'
    - '#ef4444'
    - '#f6ae50'
  brandStrength: 0.6841915857512504
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
