name: Cogwork Media
favicon: null
layout_spectrum: 0.3574957672972232
typography_spectrum: 0.39292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6841915857512504
  lightness: 0.0682218112051487
  saturation: 0.9566114258486778
  rhythmicContrast: 0.588950201170519
purpose: []
